// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: nist_sp800_22.proto

package nistsp80022v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sp80022TestService_RunTestSuite_FullMethodName = "/nist.sp800_22.v1.Sp80022TestService/RunTestSuite"
)

// Sp80022TestServiceClient is the client API for Sp80022TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for NIST SP 800-22 Rev 1a Statistical Test Suite
type Sp80022TestServiceClient interface {
	// RunTestSuite executes all 15 NIST SP 800-22 statistical tests on the provided bitstream
	RunTestSuite(ctx context.Context, in *Sp80022TestRequest, opts ...grpc.CallOption) (*Sp80022TestResponse, error)
}

type sp80022TestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSp80022TestServiceClient(cc grpc.ClientConnInterface) Sp80022TestServiceClient {
	return &sp80022TestServiceClient{cc}
}

func (c *sp80022TestServiceClient) RunTestSuite(ctx context.Context, in *Sp80022TestRequest, opts ...grpc.CallOption) (*Sp80022TestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Sp80022TestResponse)
	err := c.cc.Invoke(ctx, Sp80022TestService_RunTestSuite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Sp80022TestServiceServer is the server API for Sp80022TestService service.
// All implementations must embed UnimplementedSp80022TestServiceServer
// for forward compatibility.
//
// Service for NIST SP 800-22 Rev 1a Statistical Test Suite
type Sp80022TestServiceServer interface {
	// RunTestSuite executes all 15 NIST SP 800-22 statistical tests on the provided bitstream
	RunTestSuite(context.Context, *Sp80022TestRequest) (*Sp80022TestResponse, error)
	mustEmbedUnimplementedSp80022TestServiceServer()
}

// UnimplementedSp80022TestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSp80022TestServiceServer struct{}

func (UnimplementedSp80022TestServiceServer) RunTestSuite(context.Context, *Sp80022TestRequest) (*Sp80022TestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunTestSuite not implemented")
}
func (UnimplementedSp80022TestServiceServer) mustEmbedUnimplementedSp80022TestServiceServer() {}
func (UnimplementedSp80022TestServiceServer) testEmbeddedByValue()                            {}

// UnsafeSp80022TestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Sp80022TestServiceServer will
// result in compilation errors.
type UnsafeSp80022TestServiceServer interface {
	mustEmbedUnimplementedSp80022TestServiceServer()
}

func RegisterSp80022TestServiceServer(s grpc.ServiceRegistrar, srv Sp80022TestServiceServer) {
	// If the following call panics, it indicates UnimplementedSp80022TestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sp80022TestService_ServiceDesc, srv)
}

func _Sp80022TestService_RunTestSuite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Sp80022TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Sp80022TestServiceServer).RunTestSuite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sp80022TestService_RunTestSuite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Sp80022TestServiceServer).RunTestSuite(ctx, req.(*Sp80022TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sp80022TestService_ServiceDesc is the grpc.ServiceDesc for Sp80022TestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sp80022TestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nist.sp800_22.v1.Sp80022TestService",
	HandlerType: (*Sp80022TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunTestSuite",
			Handler:    _Sp80022TestService_RunTestSuite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nist_sp800_22.proto",
}
