// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: nist_sp800_22.proto

package nistsp80022v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sp80022TestRequest contains the bitstream and optional configuration
type Sp80022TestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw bitstream as bytes (minimum 387,840 bits)
	Bitstream []byte `protobuf:"bytes,1,opt,name=bitstream,proto3" json:"bitstream,omitempty"`
	// Optional test configuration parameters
	Config        *Sp80022TestConfig `protobuf:"bytes,2,opt,name=config,proto3,oneof" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sp80022TestRequest) Reset() {
	*x = Sp80022TestRequest{}
	mi := &file_nist_sp800_22_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sp80022TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sp80022TestRequest) ProtoMessage() {}

func (x *Sp80022TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nist_sp800_22_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sp80022TestRequest.ProtoReflect.Descriptor instead.
func (*Sp80022TestRequest) Descriptor() ([]byte, []int) {
	return file_nist_sp800_22_proto_rawDescGZIP(), []int{0}
}

func (x *Sp80022TestRequest) GetBitstream() []byte {
	if x != nil {
		return x.Bitstream
	}
	return nil
}

func (x *Sp80022TestRequest) GetConfig() *Sp80022TestConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// Sp80022TestConfig allows customization of test parameters
type Sp80022TestConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block Frequency Test - block length M (default: 128)
	BlockFrequencyBlockLength int32 `protobuf:"varint,1,opt,name=block_frequency_block_length,json=blockFrequencyBlockLength,proto3" json:"block_frequency_block_length,omitempty"`
	// Non-Overlapping Template Test - block length m (default: 9)
	NonOverlappingTemplateBlockLength int32 `protobuf:"varint,2,opt,name=non_overlapping_template_block_length,json=nonOverlappingTemplateBlockLength,proto3" json:"non_overlapping_template_block_length,omitempty"`
	// Overlapping Template Test - block length m (default: 9)
	OverlappingTemplateBlockLength int32 `protobuf:"varint,3,opt,name=overlapping_template_block_length,json=overlappingTemplateBlockLength,proto3" json:"overlapping_template_block_length,omitempty"`
	// Approximate Entropy Test - block length m (default: 10)
	ApproximateEntropyBlockLength int32 `protobuf:"varint,4,opt,name=approximate_entropy_block_length,json=approximateEntropyBlockLength,proto3" json:"approximate_entropy_block_length,omitempty"`
	// Serial Test - block length m (default: 16)
	SerialBlockLength int32 `protobuf:"varint,5,opt,name=serial_block_length,json=serialBlockLength,proto3" json:"serial_block_length,omitempty"`
	// Linear Complexity Test - sequence length M (default: 500)
	LinearComplexitySequenceLength int32 `protobuf:"varint,6,opt,name=linear_complexity_sequence_length,json=linearComplexitySequenceLength,proto3" json:"linear_complexity_sequence_length,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *Sp80022TestConfig) Reset() {
	*x = Sp80022TestConfig{}
	mi := &file_nist_sp800_22_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sp80022TestConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sp80022TestConfig) ProtoMessage() {}

func (x *Sp80022TestConfig) ProtoReflect() protoreflect.Message {
	mi := &file_nist_sp800_22_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sp80022TestConfig.ProtoReflect.Descriptor instead.
func (*Sp80022TestConfig) Descriptor() ([]byte, []int) {
	return file_nist_sp800_22_proto_rawDescGZIP(), []int{1}
}

func (x *Sp80022TestConfig) GetBlockFrequencyBlockLength() int32 {
	if x != nil {
		return x.BlockFrequencyBlockLength
	}
	return 0
}

func (x *Sp80022TestConfig) GetNonOverlappingTemplateBlockLength() int32 {
	if x != nil {
		return x.NonOverlappingTemplateBlockLength
	}
	return 0
}

func (x *Sp80022TestConfig) GetOverlappingTemplateBlockLength() int32 {
	if x != nil {
		return x.OverlappingTemplateBlockLength
	}
	return 0
}

func (x *Sp80022TestConfig) GetApproximateEntropyBlockLength() int32 {
	if x != nil {
		return x.ApproximateEntropyBlockLength
	}
	return 0
}

func (x *Sp80022TestConfig) GetSerialBlockLength() int32 {
	if x != nil {
		return x.SerialBlockLength
	}
	return 0
}

func (x *Sp80022TestConfig) GetLinearComplexitySequenceLength() int32 {
	if x != nil {
		return x.LinearComplexitySequenceLength
	}
	return 0
}

// Sp80022TestResponse contains results from all 15 NIST SP 800-22 tests
type Sp80022TestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ISO 8601 timestamp when tests were executed
	Timestamp string `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Number of bits in the input sample
	SampleSizeBits int32 `protobuf:"varint,2,opt,name=sample_size_bits,json=sampleSizeBits,proto3" json:"sample_size_bits,omitempty"`
	// Overall pass rate (0.0 - 1.0) - ONLY for implemented tests
	OverallPassRate float64 `protobuf:"fixed64,3,opt,name=overall_pass_rate,json=overallPassRate,proto3" json:"overall_pass_rate,omitempty"`
	// P-value uniformity chi-squared test result
	PValueUniformityChi2 float64 `protobuf:"fixed64,4,opt,name=p_value_uniformity_chi2,json=pValueUniformityChi2,proto3" json:"p_value_uniformity_chi2,omitempty"`
	// Individual test results (15 tests)
	Results []*Sp80022TestResult `protobuf:"bytes,5,rep,name=results,proto3" json:"results,omitempty"`
	// Total execution time in milliseconds
	ExecutionTimeMs int64 `protobuf:"varint,6,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	// Number of tests actually executed (not skipped)
	TestsRun int32 `protobuf:"varint,7,opt,name=tests_run,json=testsRun,proto3" json:"tests_run,omitempty"`
	// Number of tests not yet implemented
	TestsSkipped int32 `protobuf:"varint,8,opt,name=tests_skipped,json=testsSkipped,proto3" json:"tests_skipped,omitempty"`
	// Always 15 for NIST SP 800-22
	TestsTotal int32 `protobuf:"varint,9,opt,name=tests_total,json=testsTotal,proto3" json:"tests_total,omitempty"`
	// true only if tests_run == tests_total (full NIST SP 800-22 compliance)
	NistCompliant bool `protobuf:"varint,10,opt,name=nist_compliant,json=nistCompliant,proto3" json:"nist_compliant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sp80022TestResponse) Reset() {
	*x = Sp80022TestResponse{}
	mi := &file_nist_sp800_22_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sp80022TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sp80022TestResponse) ProtoMessage() {}

func (x *Sp80022TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nist_sp800_22_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sp80022TestResponse.ProtoReflect.Descriptor instead.
func (*Sp80022TestResponse) Descriptor() ([]byte, []int) {
	return file_nist_sp800_22_proto_rawDescGZIP(), []int{2}
}

func (x *Sp80022TestResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Sp80022TestResponse) GetSampleSizeBits() int32 {
	if x != nil {
		return x.SampleSizeBits
	}
	return 0
}

func (x *Sp80022TestResponse) GetOverallPassRate() float64 {
	if x != nil {
		return x.OverallPassRate
	}
	return 0
}

func (x *Sp80022TestResponse) GetPValueUniformityChi2() float64 {
	if x != nil {
		return x.PValueUniformityChi2
	}
	return 0
}

func (x *Sp80022TestResponse) GetResults() []*Sp80022TestResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *Sp80022TestResponse) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *Sp80022TestResponse) GetTestsRun() int32 {
	if x != nil {
		return x.TestsRun
	}
	return 0
}

func (x *Sp80022TestResponse) GetTestsSkipped() int32 {
	if x != nil {
		return x.TestsSkipped
	}
	return 0
}

func (x *Sp80022TestResponse) GetTestsTotal() int32 {
	if x != nil {
		return x.TestsTotal
	}
	return 0
}

func (x *Sp80022TestResponse) GetNistCompliant() bool {
	if x != nil {
		return x.NistCompliant
	}
	return false
}

// Sp80022TestResult represents the outcome of a single NIST SP 800-22 statistical test
type Sp80022TestResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Test name (e.g., "frequency_monobit")
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// P-value from the test (0.0 - 1.0)
	PValue float64 `protobuf:"fixed64,2,opt,name=p_value,json=pValue,proto3" json:"p_value,omitempty"`
	// Whether the test passed (p_value > 0.01)
	Passed bool `protobuf:"varint,3,opt,name=passed,proto3" json:"passed,omitempty"`
	// Proportion metric (for multi-run tests, optional)
	Proportion *float64 `protobuf:"fixed64,4,opt,name=proportion,proto3,oneof" json:"proportion,omitempty"`
	// Warning message if test couldn't complete normally
	Warning       *string `protobuf:"bytes,5,opt,name=warning,proto3,oneof" json:"warning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sp80022TestResult) Reset() {
	*x = Sp80022TestResult{}
	mi := &file_nist_sp800_22_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sp80022TestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sp80022TestResult) ProtoMessage() {}

func (x *Sp80022TestResult) ProtoReflect() protoreflect.Message {
	mi := &file_nist_sp800_22_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sp80022TestResult.ProtoReflect.Descriptor instead.
func (*Sp80022TestResult) Descriptor() ([]byte, []int) {
	return file_nist_sp800_22_proto_rawDescGZIP(), []int{3}
}

func (x *Sp80022TestResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Sp80022TestResult) GetPValue() float64 {
	if x != nil {
		return x.PValue
	}
	return 0
}

func (x *Sp80022TestResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *Sp80022TestResult) GetProportion() float64 {
	if x != nil && x.Proportion != nil {
		return *x.Proportion
	}
	return 0
}

func (x *Sp80022TestResult) GetWarning() string {
	if x != nil && x.Warning != nil {
		return *x.Warning
	}
	return ""
}

var File_nist_sp800_22_proto protoreflect.FileDescriptor

const file_nist_sp800_22_proto_rawDesc = "" +
	"\n" +
	"\x13nist_sp800_22.proto\x12\x10nist.sp800_22.v1\"\x7f\n" +
	"\x12Sp80022TestRequest\x12\x1c\n" +
	"\tbitstream\x18\x01 \x01(\fR\tbitstream\x12@\n" +
	"\x06config\x18\x02 \x01(\v2#.nist.sp800_22.v1.Sp80022TestConfigH\x00R\x06config\x88\x01\x01B\t\n" +
	"\a_config\"\xb5\x03\n" +
	"\x11Sp80022TestConfig\x12?\n" +
	"\x1cblock_frequency_block_length\x18\x01 \x01(\x05R\x19blockFrequencyBlockLength\x12P\n" +
	"%non_overlapping_template_block_length\x18\x02 \x01(\x05R!nonOverlappingTemplateBlockLength\x12I\n" +
	"!overlapping_template_block_length\x18\x03 \x01(\x05R\x1eoverlappingTemplateBlockLength\x12G\n" +
	" approximate_entropy_block_length\x18\x04 \x01(\x05R\x1dapproximateEntropyBlockLength\x12.\n" +
	"\x13serial_block_length\x18\x05 \x01(\x05R\x11serialBlockLength\x12I\n" +
	"!linear_complexity_sequence_length\x18\x06 \x01(\x05R\x1elinearComplexitySequenceLength\"\xb5\x03\n" +
	"\x13Sp80022TestResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12(\n" +
	"\x10sample_size_bits\x18\x02 \x01(\x05R\x0esampleSizeBits\x12*\n" +
	"\x11overall_pass_rate\x18\x03 \x01(\x01R\x0foverallPassRate\x125\n" +
	"\x17p_value_uniformity_chi2\x18\x04 \x01(\x01R\x14pValueUniformityChi2\x12=\n" +
	"\aresults\x18\x05 \x03(\v2#.nist.sp800_22.v1.Sp80022TestResultR\aresults\x12*\n" +
	"\x11execution_time_ms\x18\x06 \x01(\x03R\x0fexecutionTimeMs\x12\x1b\n" +
	"\ttests_run\x18\a \x01(\x05R\btestsRun\x12#\n" +
	"\rtests_skipped\x18\b \x01(\x05R\ftestsSkipped\x12\x1f\n" +
	"\vtests_total\x18\t \x01(\x05R\n" +
	"testsTotal\x12%\n" +
	"\x0enist_compliant\x18\n" +
	" \x01(\bR\rnistCompliant\"\xb7\x01\n" +
	"\x11Sp80022TestResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\ap_value\x18\x02 \x01(\x01R\x06pValue\x12\x16\n" +
	"\x06passed\x18\x03 \x01(\bR\x06passed\x12#\n" +
	"\n" +
	"proportion\x18\x04 \x01(\x01H\x00R\n" +
	"proportion\x88\x01\x01\x12\x1d\n" +
	"\awarning\x18\x05 \x01(\tH\x01R\awarning\x88\x01\x01B\r\n" +
	"\v_proportionB\n" +
	"\n" +
	"\b_warning2q\n" +
	"\x12Sp80022TestService\x12[\n" +
	"\fRunTestSuite\x12$.nist.sp800_22.v1.Sp80022TestRequest\x1a%.nist.sp800_22.v1.Sp80022TestResponseBEZCgithub.com/AmmannChristian/nist-sp800-22-rev1a/pkg/pb;nistsp80022v1b\x06proto3"

var (
	file_nist_sp800_22_proto_rawDescOnce sync.Once
	file_nist_sp800_22_proto_rawDescData []byte
)

func file_nist_sp800_22_proto_rawDescGZIP() []byte {
	file_nist_sp800_22_proto_rawDescOnce.Do(func() {
		file_nist_sp800_22_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nist_sp800_22_proto_rawDesc), len(file_nist_sp800_22_proto_rawDesc)))
	})
	return file_nist_sp800_22_proto_rawDescData
}

var file_nist_sp800_22_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_nist_sp800_22_proto_goTypes = []any{
	(*Sp80022TestRequest)(nil),  // 0: nist.sp800_22.v1.Sp80022TestRequest
	(*Sp80022TestConfig)(nil),   // 1: nist.sp800_22.v1.Sp80022TestConfig
	(*Sp80022TestResponse)(nil), // 2: nist.sp800_22.v1.Sp80022TestResponse
	(*Sp80022TestResult)(nil),   // 3: nist.sp800_22.v1.Sp80022TestResult
}
var file_nist_sp800_22_proto_depIdxs = []int32{
	1, // 0: nist.sp800_22.v1.Sp80022TestRequest.config:type_name -> nist.sp800_22.v1.Sp80022TestConfig
	3, // 1: nist.sp800_22.v1.Sp80022TestResponse.results:type_name -> nist.sp800_22.v1.Sp80022TestResult
	0, // 2: nist.sp800_22.v1.Sp80022TestService.RunTestSuite:input_type -> nist.sp800_22.v1.Sp80022TestRequest
	2, // 3: nist.sp800_22.v1.Sp80022TestService.RunTestSuite:output_type -> nist.sp800_22.v1.Sp80022TestResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_nist_sp800_22_proto_init() }
func file_nist_sp800_22_proto_init() {
	if File_nist_sp800_22_proto != nil {
		return
	}
	file_nist_sp800_22_proto_msgTypes[0].OneofWrappers = []any{}
	file_nist_sp800_22_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nist_sp800_22_proto_rawDesc), len(file_nist_sp800_22_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nist_sp800_22_proto_goTypes,
		DependencyIndexes: file_nist_sp800_22_proto_depIdxs,
		MessageInfos:      file_nist_sp800_22_proto_msgTypes,
	}.Build()
	File_nist_sp800_22_proto = out.File
	file_nist_sp800_22_proto_goTypes = nil
	file_nist_sp800_22_proto_depIdxs = nil
}
